[ui]
theme = "base24-catppuccin-mocha"

[preview]
revision_command = [
  "show",
  "--color",
  "always",
  "-r",
  "$change_id",
  "--config",
  "ui.diff-formatter=delta-non-split-view",
]
file_command = [
  "diff",
  "--color",
  "always",
  "-r",
  "$change_id",
  "$file",
  "--config",
  "ui.diff-formatter=delta-non-split-view",
]

[[actions]]
name = "revisions.diff"
desc = "diff"
lua = '''
jj_interactive("diff", "-r", context.change_id(), "--config", "ui.pager=diffnav")
'''

[[actions]]
name = "revisions.details.diff"
desc = "diff"
lua = '''
jj_interactive("diff", "-r", context.change_id(), context.file(), "--config", "ui.pager=diffnav")
'''
