[user]
name = "Nan Huang"
email = "teddyhuangnan@gmail.com"

[[--scope]]
--when.commands = ["status"]
[--scope.ui]
paginate = "never"
[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "diffnav"
diff-formatter = ":git"

[merge-tools.delta-non-split-view]
program = "delta"
diff-args = [
  "--width",
  "$width",
  "--features",
  "non-split-view catppuccin-mocha",
  "$left",
  "$right",
]

[ui]
default-command = "log"
